version: "3.8"

services:
  api:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: render-api
    command: uvicorn render_rig2.api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env


  worker_all:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: render-worker-all
    command: celery -A render_rig2.app_v2 worker -n all@%h -Q lookup_chart_registry,get_existing_chart,lookup_log_registry,get_log_dispatch_chart,store_log_chart -c 2 --loglevel=info --prefetch-multiplier=1
    env_file:
      - .env
  # worker_lookup:
  #     platform: linux/arm64
  #     build:
  #       context: .
  #       dockerfile: Dockerfile
  #     container_name: render-worker-lookup
  #     command: celery -A render_rig2.app_v2 worker -n lookup@%h -Q lookup_chart_registry -c 2 --loglevel=info --prefetch-multiplier=1
  #     env_file:
  #       - .env
  
  
  # worker_get_existing_chart:
  #     platform: linux/arm64
  #     build:
  #       context: .
  #       dockerfile: Dockerfile
  #     container_name: render-worker-get-existing-chart
  #     command: celery -A render_rig2.app_v2 worker -n get_existing_chart@%h -Q get_existing_chart -c 2 --loglevel=info --prefetch-multiplier=1
  #     env_file:
  #       - .env

  # worker_lookup_log_registry:
  #   platform: linux/arm64
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: render-worker-lookup-log-registry
  #   command: celery -A render_rig2.app_v2 worker -n lookup_log_registry@%h -Q lookup_log_registry -c 2 --loglevel=info --prefetch-multiplier=1
  #   env_file:
  #     - .env
  
  # worker_get_log_dispatch_chart:
  #   platform: linux/arm64
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: render-worker-get-log-dispatch-chart
  #   command: celery -A render_rig2.app_v2 worker -n get_log_dispatch_chart@%h -Q get_log_dispatch_chart -c 2 --loglevel=info --prefetch-multiplier=1
  #   env_file:
  #     - .env

  # worker_store:
  #   platform: linux/arm64
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: render-worker-store
  #   command: celery -A render_rig2.app_v2 worker -n store@%h -Q store_log_chart -c 1 --loglevel=info --prefetch-multiplier=1
  #   env_file:
  #     - .env
  
  flower:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: render-flower
    command: celery -A render_rig2.app_v2 flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      # - worker_lookup
      # - worker_get_existing_chart
      # - worker_lookup_log_registry
      # - worker_get_log_dispatch_chart
      # - worker_store
      - worker_all

networks:
  default:
    external: true
    name: redis_default