version: "3.8"

services:
  api:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: render-api
    command: uvicorn render_rig2.api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env

  worker:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: render-worker
    command: celery -A render_rig2.app worker -Q lookup_chart_registry,get_existing_chart,lookup_log_registry,get_log_dispatch_chart,store_log_chart -c 6 --loglevel=info
    env_file:
      - .env
  
  flower:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: render-flower
    command: celery -A render_rig2.app flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - worker

networks:
  default:
    external: true
    name: redis_default