[project]
name = "render_rig"
version = "0.1.0"
description = "Chart rendering rig for log_foundry"
authors = [{ name = "Nikhil", email = "nikhil@yawpitchroll.ai" }]
dependencies = ["boto3", "fastapi"]
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["."]
include = ["render_rig"]